# Generated by Django 4.1.4 on 2022-12-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='request',
            new_name='req',
        ),
    ]
