# Generated by Django 4.1.4 on 2022-12-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
